<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container60MtWCD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container60MtWCD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container60MtWCD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container60MtWCD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container60MtWCD\App_KernelDevDebugContainer([
    'container.build_hash' => '60MtWCD',
    'container.build_id' => '85717faf',
    'container.build_time' => 1584547140,
], __DIR__.\DIRECTORY_SEPARATOR.'Container60MtWCD');
