<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5TxYCgg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5TxYCgg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5TxYCgg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5TxYCgg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5TxYCgg\App_KernelDevDebugContainer([
    'container.build_hash' => '5TxYCgg',
    'container.build_id' => '7025b236',
    'container.build_time' => 1584608705,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5TxYCgg');
