<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9ozZIda\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9ozZIda/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9ozZIda.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9ozZIda\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9ozZIda\App_KernelDevDebugContainer([
    'container.build_hash' => '9ozZIda',
    'container.build_id' => '373297c4',
    'container.build_time' => 1584573527,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9ozZIda');
