<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'api_cours' => [[], ['_controller' => 'App\\Controller\\Api\\CoursController::getCours'], [], [['text', '/api/cours']], [], []],
    'api_put_cours' => [[], ['_controller' => 'App\\Controller\\Api\\CoursController::createCours'], [], [['text', '/api/cours/create']], [], []],
    'api_cours_id' => [['id'], ['_controller' => 'App\\Controller\\Api\\CoursController::getUnCours'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/cours']], [], []],
    'api_cours_id_edit' => [['id'], ['_controller' => 'App\\Controller\\Api\\CoursController::editUnCours'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/cours']], [], []],
    'api_delete_cours' => [['id'], ['_controller' => 'App\\Controller\\Api\\CoursController::deleteCours'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/cours']], [], []],
    'api_professeurs' => [[], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::getProfesseurs'], [], [['text', '/api/professeurs']], [], []],
    'api_professeurs_id' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::getProfesseur'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], []],
    'api_get_professeurs_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::getProfesseurAvis'], [], [['text', '/avis'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], []],
    'api_get_professeurs_cours' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::getProfesseurCours'], [], [['text', '/cours'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], []],
    'api_put_professeurs_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::putProfesseurAvis'], [], [['text', '/avis'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], []],
    'api_delete_professeurs_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::deleteAvis'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/avis']], [], []],
    'api_matieres' => [[], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::getMatieres'], [], [['text', '/api/matieres']], [], []],
    'api_salles' => [[], ['_controller' => 'App\\Controller\\Api\\SalleController::getCours'], [], [['text', '/api/salles']], [], []],
    'api_salles_id' => [['id'], ['_controller' => 'App\\Controller\\Api\\SalleController::getUneSalle'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/salles']], [], []],
    'api_delete_salles' => [['id'], ['_controller' => 'App\\Controller\\Api\\SalleController::deleteSalle'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/salles']], [], []],
    'api_put_salles' => [[], ['_controller' => 'App\\Controller\\Api\\SalleController::createSalle'], [], [['text', '/api/salles/create']], [], []],
    'professeurs' => [[], ['_controller' => 'App\\Controller\\ProfesseurController::index'], [], [['text', '/professeurs/']], [], []],
    'professeurs.create' => [[], ['_controller' => 'App\\Controller\\ProfesseurController::create'], [], [['text', '/professeurs/create']], [], []],
    'professeurs.edit' => [['id'], ['_controller' => 'App\\Controller\\ProfesseurController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/professeurs']], [], []],
    'professeurs.delete' => [['id'], ['_controller' => 'App\\Controller\\ProfesseurController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/professeurs']], [], []],
    'easyadmin' => [[], ['_controller' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Controller\\EasyAdminController::indexAction'], [], [['text', '/admin/']], [], []],
];
